version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - /var/lib/postgresql/data   # anonymous volume, not persisted
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:

